import Head from 'next/head'
import Image from "next/image";
import Link from "next/link";
import styles from '../styles/Home.module.css'



import {fromImageToUrl, API_URL} from "../utils/urls";
import {twoDecimals} from "../utils/format";

export default function Home({products}) {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {products.map(product => (
            <div className={styles.product} key={product.id}>
                <Link href={`/product/${product.slug}`}>
                    <a>
                    <div className={styles.product__Rows}>
                    <div className={styles.product__ColImg}>
                        <Image src={fromImageToUrl(product.image)} width={1200} height={1200} />
                    </div>
                    <div className={styles.product__Col}>{product.name} ${twoDecimals(product.price)}</div>
                </div>
                    </a>
                </Link>
            </div>
        ))}
      </div>


  )
}
export async function getStaticProps() {
    const res = await fetch(`${API_URL}/products`)
    const products = await res.json()
    return {
        props: {products}
    }
}
